version: '3.8'

services:
  backend:
    build: ./backend
    container_name: library-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - database
    networks:
      - library-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: library-frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - library-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

  database:
    image: postgres:15
    container_name: library-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    networks:
      - library-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  library-network:

volumes:
  postgres-data:
